// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-DNBId2iHN8tcLAEuOogsfIjU94MfaBI',
    appId: '1:84455423596:web:24a5961a207ed645ae2249',
    messagingSenderId: '84455423596',
    projectId: 'mingl-6c303',
    authDomain: 'mingl-6c303.firebaseapp.com',
    storageBucket: 'mingl-6c303.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVESxdU-NSLy-5uWJEWpexJq7d0N7wWqg',
    appId: '1:84455423596:android:661428d82d2dc639ae2249',
    messagingSenderId: '84455423596',
    projectId: 'mingl-6c303',
    storageBucket: 'mingl-6c303.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFqdXXqpemOJqUROEExDP8pt3ys1GhAws',
    appId: '1:84455423596:ios:2cb84dfa4670957dae2249',
    messagingSenderId: '84455423596',
    projectId: 'mingl-6c303',
    storageBucket: 'mingl-6c303.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFqdXXqpemOJqUROEExDP8pt3ys1GhAws',
    appId: '1:84455423596:ios:2cb84dfa4670957dae2249',
    messagingSenderId: '84455423596',
    projectId: 'mingl-6c303',
    storageBucket: 'mingl-6c303.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-DNBId2iHN8tcLAEuOogsfIjU94MfaBI',
    appId: '1:84455423596:web:dfb665d1ef0774dbae2249',
    messagingSenderId: '84455423596',
    projectId: 'mingl-6c303',
    authDomain: 'mingl-6c303.firebaseapp.com',
    storageBucket: 'mingl-6c303.appspot.com',
  );

}